global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: localhost

  - job_name: warehouse
    scrape_interval: 5s
    static_configs:
      - targets: ['warehouse-service:3030']
        labels:
          instance: localhost