{
 "title": "仓库环境监测面板",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "服务器运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"localhost\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"localhost\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"localhost\"} / (node_memory_MemTotal_bytes{instance=~\"localhost\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{instance=\"localhost\",fstype=~\"ext4|xfs\",device=\"/dev/vda1\",mountpoint=\"/rootfs\"} / node_filesystem_size_bytes{instance='localhost',fstype=~\"ext4|xfs\",device=\"/dev/vda1\",mountpoint=\"/rootfs\"}))*100",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "设备列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "targets": [
    { "expr": "warehouse_mqtt{}-0" }
   ]
  },
  {
   "title": "服务日志",
   "type": "logs",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/warehouse.log\"}"
    }
   ]
  },
  {
   "title": "已用内存",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"localhost\"}"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"localhost\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 6 },
   "content": "<div class=\"dashboard-header\">\n  <span>一号仓库</span>\n</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 6 },
   "content": "<div class=\"dashboard-header\">\n  <span>二号仓库</span>\n</div>\n"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"2\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"2\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"2\"}"
    }
   ]
  },
  {
   "title": "一号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"1\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"1\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"1\"}",
     "legendFormat": "空气质量"
    }
   ]
  },
  {
   "title": "二号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"2\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"2\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"2\"}",
     "legendFormat": "空气质量"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 21 },
   "content": "<div class=\"dashboard-header\">\n  <span>三号仓库</span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 21 },
   "content": "<div class=\"dashboard-header\">\n  <span>四号仓库</span>\n</div>\n"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"3\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 23 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"3\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"3\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"4\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"4\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 23 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"4\"}"
    }
   ]
  },
  {
   "title": "三号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"3\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"3\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"3\"}",
     "legendFormat": "空气质量"
    }
   ]
  },
  {
   "title": "四号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"4\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"4\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"4\"}",
     "legendFormat": "空气质量"
    }
   ]
  }
 ]
}