{
 "title": "仓库环境监测面板（移动端）",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"localhost\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"localhost\"} / (node_memory_MemTotal_bytes{instance=~\"localhost\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(1-(node_filesystem_free_bytes{instance=\"localhost\",fstype=~\"ext4|xfs\",device=\"/dev/vda1\",mountpoint=\"/rootfs\"} / node_filesystem_size_bytes{instance='localhost',fstype=~\"ext4|xfs\",device=\"/dev/vda1\",mountpoint=\"/rootfs\"}))*100",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "设备列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "targets": [
    { "expr": "warehouse_mqtt{}-0" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 6 },
   "content": "<div class=\"dashboard-header\">\n  <span>一号仓库</span>\n</div>\n"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"1\"}"
    }
   ]
  },
  {
   "title": "一号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"1\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"1\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"1\"}",
     "legendFormat": "空气质量"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 15 },
   "content": "<div class=\"dashboard-header\">\n  <span>二号仓库</span>\n</div>\n"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"2\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"2\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"2\"}"
    }
   ]
  },
  {
   "title": "二号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"2\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"2\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"2\"}",
     "legendFormat": "空气质量"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 24 },
   "content": "<div class=\"dashboard-header\">\n  <span>三号仓库</span>\n</div>"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"3\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 26 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"3\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"3\"}"
    }
   ]
  },
  {
   "title": "三号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"3\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"3\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"3\"}",
     "legendFormat": "空气质量"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 33 },
   "content": "<div class=\"dashboard-header\">\n  <span>四号仓库</span>\n</div>\n"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"4\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 35 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"4\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"4\"}"
    }
   ]
  },
  {
   "title": "四号仓库",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"4\"}",
     "legendFormat": "湿度"
    },
    {
     "expr": "warehouse_temp{id=\"4\"}",
     "legendFormat": "温度"
    },
    {
     "expr": "warehouse_mq135{id=\"4\"}",
     "legendFormat": "空气质量"
    }
   ]
  }
 ]
}