{
 "title": "仓库环境监测（单仓库）",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "仓库编号",
    "query": "label_values(warehouse_mqtt, id)"
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "warehouse_temp{id=\"$id\"}"
    }
   ]
  },
  {
   "title": "温度",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_temp{id=\"$id\"}",
     "legendFormat": "温度"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "warehouse_hum{id=\"$id\"}"
    }
   ]
  },
  {
   "title": "湿度",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_hum{id=\"$id\"}",
     "legendFormat": "湿度"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"$id\"}"
    }
   ]
  },
  {
   "title": "空气质量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "warehouse_mq135{id=\"$id\"}",
     "legendFormat": "空气质量"
    }
   ]
  }
 ]
}